version: '2'
services:
    powercripto-app:
        image: powercripto
        external_links:
            - powercripto-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/powercripto
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    powercripto-postgresql:
        extends:
            file: postgresql.yml
            service: powercripto-postgresql
